package de.beachboys.aoc2021;

import de.beachboys.Day;
import de.beachboys.DayTest;
import de.beachboys.IOHelper;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;
import java.util.List;
import java.util.stream.Stream;

public class Day24Test extends DayTest {

    private final Day day = new Day24();

    private static Stream<Arguments> provideTestDataForPart1() {
        return Stream.of(
                Arguments.of(List.of("inp w",
                        "mul x 0",
                        "add x z",
                        "mod x 26",
                        "div z 1",
                        "add x 11",
                        "eql x w",
                        "eql x 0",
                        "mul y 0",
                        "add y 25",
                        "mul y x",
                        "add y 1",
                        "mul z y",
                        "mul y 0",
                        "add y w",
                        "add y 6",
                        "mul y x",
                        "add z y",
                        "inp w",
                        "mul x 0",
                        "add x z",
                        "mod x 26",
                        "div z 1",
                        "add x 13",
                        "eql x w",
                        "eql x 0",
                        "mul y 0",
                        "add y 25",
                        "mul y x",
                        "add y 1",
                        "mul z y",
                        "mul y 0",
                        "add y w",
                        "add y 14",
                        "mul y x",
                        "add z y",
                        "inp w",
                        "mul x 0",
                        "add x z",
                        "mod x 26",
                        "div z 1",
                        "add x 15",
                        "eql x w",
                        "eql x 0",
                        "mul y 0",
                        "add y 25",
                        "mul y x",
                        "add y 1",
                        "mul z y",
                        "mul y 0",
                        "add y w",
                        "add y 14",
                        "mul y x",
                        "add z y",
                        "inp w",
                        "mul x 0",
                        "add x z",
                        "mod x 26",
                        "div z 26",
                        "add x -8",
                        "eql x w",
                        "eql x 0",
                        "mul y 0",
                        "add y 25",
                        "mul y x",
                        "add y 1",
                        "mul z y",
                        "mul y 0",
                        "add y w",
                        "add y 10",
                        "mul y x",
                        "add z y",
                        "inp w",
                        "mul x 0",
                        "add x z",
                        "mod x 26",
                        "div z 1",
                        "add x 13",
                        "eql x w",
                        "eql x 0",
                        "mul y 0",
                        "add y 25",
                        "mul y x",
                        "add y 1",
                        "mul z y",
                        "mul y 0",
                        "add y w",
                        "add y 9",
                        "mul y x",
                        "add z y",
                        "inp w",
                        "mul x 0",
                        "add x z",
                        "mod x 26",
                        "div z 1",
                        "add x 15",
                        "eql x w",
                        "eql x 0",
                        "mul y 0",
                        "add y 25",
                        "mul y x",
                        "add y 1",
                        "mul z y",
                        "mul y 0",
                        "add y w",
                        "add y 12",
                        "mul y x",
                        "add z y",
                        "inp w",
                        "mul x 0",
                        "add x z",
                        "mod x 26",
                        "div z 26",
                        "add x -11",
                        "eql x w",
                        "eql x 0",
                        "mul y 0",
                        "add y 25",
                        "mul y x",
                        "add y 1",
                        "mul z y",
                        "mul y 0",
                        "add y w",
                        "add y 8",
                        "mul y x",
                        "add z y",
                        "inp w",
                        "mul x 0",
                        "add x z",
                        "mod x 26",
                        "div z 26",
                        "add x -4",
                        "eql x w",
                        "eql x 0",
                        "mul y 0",
                        "add y 25",
                        "mul y x",
                        "add y 1",
                        "mul z y",
                        "mul y 0",
                        "add y w",
                        "add y 13",
                        "mul y x",
                        "add z y",
                        "inp w",
                        "mul x 0",
                        "add x z",
                        "mod x 26",
                        "div z 26",
                        "add x -15",
                        "eql x w",
                        "eql x 0",
                        "mul y 0",
                        "add y 25",
                        "mul y x",
                        "add y 1",
                        "mul z y",
                        "mul y 0",
                        "add y w",
                        "add y 12",
                        "mul y x",
                        "add z y",
                        "inp w",
                        "mul x 0",
                        "add x z",
                        "mod x 26",
                        "div z 1",
                        "add x 14",
                        "eql x w",
                        "eql x 0",
                        "mul y 0",
                        "add y 25",
                        "mul y x",
                        "add y 1",
                        "mul z y",
                        "mul y 0",
                        "add y w",
                        "add y 6",
                        "mul y x",
                        "add z y",
                        "inp w",
                        "mul x 0",
                        "add x z",
                        "mod x 26",
                        "div z 1",
                        "add x 14",
                        "eql x w",
                        "eql x 0",
                        "mul y 0",
                        "add y 25",
                        "mul y x",
                        "add y 1",
                        "mul z y",
                        "mul y 0",
                        "add y w",
                        "add y 9",
                        "mul y x",
                        "add z y",
                        "inp w",
                        "mul x 0",
                        "add x z",
                        "mod x 26",
                        "div z 26",
                        "add x -1",
                        "eql x w",
                        "eql x 0",
                        "mul y 0",
                        "add y 25",
                        "mul y x",
                        "add y 1",
                        "mul z y",
                        "mul y 0",
                        "add y w",
                        "add y 15",
                        "mul y x",
                        "add z y",
                        "inp w",
                        "mul x 0",
                        "add x z",
                        "mod x 26",
                        "div z 26",
                        "add x -8",
                        "eql x w",
                        "eql x 0",
                        "mul y 0",
                        "add y 25",
                        "mul y x",
                        "add y 1",
                        "mul z y",
                        "mul y 0",
                        "add y w",
                        "add y 4",
                        "mul y x",
                        "add z y",
                        "inp w",
                        "mul x 0",
                        "add x z",
                        "mod x 26",
                        "div z 26",
                        "add x -14",
                        "eql x w",
                        "eql x 0",
                        "mul y 0",
                        "add y 25",
                        "mul y x",
                        "add y 1",
                        "mul z y",
                        "mul y 0",
                        "add y w",
                        "add y 10",
                        "mul y x",
                        "add z y"), "99394899891971", null)

        );
    }

    private static Stream<Arguments> provideTestDataForPart2() {
        return Stream.of(
                Arguments.of(List.of("inp w",
                        "mul x 0",
                        "add x z",
                        "mod x 26",
                        "div z 1",
                        "add x 11",
                        "eql x w",
                        "eql x 0",
                        "mul y 0",
                        "add y 25",
                        "mul y x",
                        "add y 1",
                        "mul z y",
                        "mul y 0",
                        "add y w",
                        "add y 6",
                        "mul y x",
                        "add z y",
                        "inp w",
                        "mul x 0",
                        "add x z",
                        "mod x 26",
                        "div z 1",
                        "add x 13",
                        "eql x w",
                        "eql x 0",
                        "mul y 0",
                        "add y 25",
                        "mul y x",
                        "add y 1",
                        "mul z y",
                        "mul y 0",
                        "add y w",
                        "add y 14",
                        "mul y x",
                        "add z y",
                        "inp w",
                        "mul x 0",
                        "add x z",
                        "mod x 26",
                        "div z 1",
                        "add x 15",
                        "eql x w",
                        "eql x 0",
                        "mul y 0",
                        "add y 25",
                        "mul y x",
                        "add y 1",
                        "mul z y",
                        "mul y 0",
                        "add y w",
                        "add y 14",
                        "mul y x",
                        "add z y",
                        "inp w",
                        "mul x 0",
                        "add x z",
                        "mod x 26",
                        "div z 26",
                        "add x -8",
                        "eql x w",
                        "eql x 0",
                        "mul y 0",
                        "add y 25",
                        "mul y x",
                        "add y 1",
                        "mul z y",
                        "mul y 0",
                        "add y w",
                        "add y 10",
                        "mul y x",
                        "add z y",
                        "inp w",
                        "mul x 0",
                        "add x z",
                        "mod x 26",
                        "div z 1",
                        "add x 13",
                        "eql x w",
                        "eql x 0",
                        "mul y 0",
                        "add y 25",
                        "mul y x",
                        "add y 1",
                        "mul z y",
                        "mul y 0",
                        "add y w",
                        "add y 9",
                        "mul y x",
                        "add z y",
                        "inp w",
                        "mul x 0",
                        "add x z",
                        "mod x 26",
                        "div z 1",
                        "add x 15",
                        "eql x w",
                        "eql x 0",
                        "mul y 0",
                        "add y 25",
                        "mul y x",
                        "add y 1",
                        "mul z y",
                        "mul y 0",
                        "add y w",
                        "add y 12",
                        "mul y x",
                        "add z y",
                        "inp w",
                        "mul x 0",
                        "add x z",
                        "mod x 26",
                        "div z 26",
                        "add x -11",
                        "eql x w",
                        "eql x 0",
                        "mul y 0",
                        "add y 25",
                        "mul y x",
                        "add y 1",
                        "mul z y",
                        "mul y 0",
                        "add y w",
                        "add y 8",
                        "mul y x",
                        "add z y",
                        "inp w",
                        "mul x 0",
                        "add x z",
                        "mod x 26",
                        "div z 26",
                        "add x -4",
                        "eql x w",
                        "eql x 0",
                        "mul y 0",
                        "add y 25",
                        "mul y x",
                        "add y 1",
                        "mul z y",
                        "mul y 0",
                        "add y w",
                        "add y 13",
                        "mul y x",
                        "add z y",
                        "inp w",
                        "mul x 0",
                        "add x z",
                        "mod x 26",
                        "div z 26",
                        "add x -15",
                        "eql x w",
                        "eql x 0",
                        "mul y 0",
                        "add y 25",
                        "mul y x",
                        "add y 1",
                        "mul z y",
                        "mul y 0",
                        "add y w",
                        "add y 12",
                        "mul y x",
                        "add z y",
                        "inp w",
                        "mul x 0",
                        "add x z",
                        "mod x 26",
                        "div z 1",
                        "add x 14",
                        "eql x w",
                        "eql x 0",
                        "mul y 0",
                        "add y 25",
                        "mul y x",
                        "add y 1",
                        "mul z y",
                        "mul y 0",
                        "add y w",
                        "add y 6",
                        "mul y x",
                        "add z y",
                        "inp w",
                        "mul x 0",
                        "add x z",
                        "mod x 26",
                        "div z 1",
                        "add x 14",
                        "eql x w",
                        "eql x 0",
                        "mul y 0",
                        "add y 25",
                        "mul y x",
                        "add y 1",
                        "mul z y",
                        "mul y 0",
                        "add y w",
                        "add y 9",
                        "mul y x",
                        "add z y",
                        "inp w",
                        "mul x 0",
                        "add x z",
                        "mod x 26",
                        "div z 26",
                        "add x -1",
                        "eql x w",
                        "eql x 0",
                        "mul y 0",
                        "add y 25",
                        "mul y x",
                        "add y 1",
                        "mul z y",
                        "mul y 0",
                        "add y w",
                        "add y 15",
                        "mul y x",
                        "add z y",
                        "inp w",
                        "mul x 0",
                        "add x z",
                        "mod x 26",
                        "div z 26",
                        "add x -8",
                        "eql x w",
                        "eql x 0",
                        "mul y 0",
                        "add y 25",
                        "mul y x",
                        "add y 1",
                        "mul z y",
                        "mul y 0",
                        "add y w",
                        "add y 4",
                        "mul y x",
                        "add z y",
                        "inp w",
                        "mul x 0",
                        "add x z",
                        "mod x 26",
                        "div z 26",
                        "add x -14",
                        "eql x w",
                        "eql x 0",
                        "mul y 0",
                        "add y 25",
                        "mul y x",
                        "add y 1",
                        "mul z y",
                        "mul y 0",
                        "add y w",
                        "add y 10",
                        "mul y x",
                        "add z y"), "92171126131911", null)

        );
    }

    @ParameterizedTest
    @MethodSource("provideTestDataForPart1")
    public void testPart1(List<String> input, Object expected, IOHelper io) {
        testPart1(this.day, input, expected, io);
    }

    @ParameterizedTest
    @MethodSource("provideTestDataForPart2")
    public void testPart2(List<String> input, Object expected, IOHelper io) {
        testPart2(this.day, input, expected, io);
    }

}